// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-visual/FloatingPhotos.tsx": () => import("../components/mockups/hero-visual/FloatingPhotos.tsx"),
  "./components/mockups/hero-visual/GiftIllustration.tsx": () => import("../components/mockups/hero-visual/GiftIllustration.tsx"),
  "./components/mockups/hero-visual/StatsCards.tsx": () => import("../components/mockups/hero-visual/StatsCards.tsx")
};
